env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - eslint
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - @typescript-eslint
  - prettier
rules: {}
settings:
  import/resolver:
    typescript: {}
