version: '3'
services:
  api:
    build: ./api
    ports:
      - "9292:9292"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fariji
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - fariji

  client:
    build: ./client
    ports:
      - "5173:5173"
    restart: on-failure
    networks:
      - fariji


  nginx:
    restart: always
    depends_on:
      - api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - fariji

networks:
  fariji:
    driver: local
volumes:
  postgres_data: