version: '3.9'
services:
  
  web-test:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    depends_on:
      - api-test
    env_file:
      - .env.test

  api-test:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on:
      - db-test
    env_file:
      - .env.test
  
  db-test:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_TEST}