require:
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/**'
    - 'app/models/*'
    - 'app/controllers/graphql_controller.rb'
    - 'app/graphql/**/**'
    - 'db/**/**'
    - 'config/**/**'
    - 'bin/**/**'
  