name: API
on:
  workflow_dispatch:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: false
      - run: make api-gem-setup
      - run: |
            cd api 
            RAILS_ENV=test rails db:create && rails db:migrate
            rspec spec/
        env:
          DB_NAME: "api_test"
          DB_USER: "postgres"
          DB_PASSWORD: "postgres"
          DB_NAME_TEST: "api_test"
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/api_test?user=postgres&password=postgres"

  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: false
      - run: make api-gem-setup
      - run: make api-lint-check